import "./globals.css"
import { Inter } from "next/font/google"
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="h-screen items-start p-36 bg-[#0c0c0c] text-[#f5f5f5] font-retro">
					<div
						className="flex flex-row h-full  border-white border-2"
						id="content"
					>
						<div id="sidebar" className="w-1/4 p-10 border-r-2">
						<ul>
							<li>
								<Link href="posts">
									Posts
								</Link>
							</li>
							<li>
								<Link href="music">
									Music
								</Link>
							</li>
							<li>
								<Link href="about">
									About
								</Link>
							</li>
						</ul>
						</div>

						<div id="content" className="w-3/4 p-10">
							{children}
						</div>
					</div>
				</main>
			</body>
		</html>
	)
}
