import "./globals.css"
import { Inter } from "next/font/google"
import Link from "next/link"
import Image from "next/image"

import jones from "../images/jones.png"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
	title: "Jorm's Gehenna",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main className="h-screen items-start p-36 px-72 bg-[#0c0c0c] text-[#f5f5f5] font-retro">
					<div
						className="flex flex-row h-full  border-white border-2"
						id="content"
					>
						<div id="sidebar" className="w-1/5 p-10 border-r-2">
							<div className="h-1/3 relative">
								<Image
									src={jones}
									alt="Jones"
									fill
									objectFit="contain"
									className="p-1"
								></Image>
							</div>
							<div className="h-1/3 flex items-center">
								<ul className="m-auto">
									<li className="py-2">
										<Link href="posts">Posts</Link>
									</li>
									<li className="py-2">
										<Link href="music">Music</Link>
									</li>
									<li className="py-2">
										<Link href="about">About</Link>
									</li>
								</ul>
							</div>
							<div className="h-1/3"></div>
						</div>

						<div id="content" className="w-4/5 p-10">
							{children}
						</div>
					</div>
				</main>
			</body>
		</html>
	)
}
